### ISSUE TITLE
GITHUB_USERNAME

### ISSUE THREAD

**Issue by Nisarg-Mehta28** [clubgamma/micro-interactions-with-css-animations#9]
## Query

*Please describe your query. How can we help you?* <br>
how can i submit my work?

**Comment by jayskhatri** [comment]
Hey @white-devil0201 👋,

First [Fork](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo) this [repository](https://github.com/clubgamma/micro-interactions-with-css-animations) then follow the steps mentioned in [README.md](https://github.com/clubgamma/micro-interactions-with-css-animations#how-to-submit-your-work-). In last make pull request, and you are in✨

**Comment by jayskhatri** [comment]
I hope you are clear with your queries and doubts, on seeing the [Submission](https://github.com/clubgamma/micro-interactions-with-css-animations/pull/18)👏👏

After reviewing, PR will be merged, I'll proceed to close this issue👍

**Comment by Nisarg-Mehta28** [comment]
Yes you have cleared my doughts thank you for your help
